/**
 * Rewaa's import templates for "Ready to upload", copied cell for cell from the
 * templates the product owner supplied on 2026-10-06 (`simple.xlsx`,
 * `Final compsite.xlsx`; kept as `tests/fixtures/ready-to-upload/`). GENERATED
 * from those files, not typed — a test reads the fixtures and requires these to
 * be identical, header for header and in order. Never rename or reorder: the
 * importer reads these exact names.
 *
 * Note: this Simple template has 45 columns (`Image URLs`, `Online Price`
 * included); OCR → Rewaa's older REWAA_SIMPLE_HEADERS has 43 and is not used here.
 */

/** The sheet name inside both templates. */
export const UPLOAD_SHEET_NAME = "data";

export const SIMPLE_UPLOAD_HEADERS = [
  "Product Name",
  "Product SKU",
  "Barcode",
  "Category",
  "Supplier",
  "Brand",
  "Description",
  "Image URLs",
  "Sellable",
  "Purchasable",
  "Enable stock management",
  "Weighted",
  "Tracked by batch",
  "Tracked by serial",
  "Retail Price",
  "Wholesale Price",
  "Online Price",
  "Cost",
  "Buy Price",
  "Tax Code",
  "DEF Quantity",
  "Pack1 Label",
  "Pack1 Size",
  "Pack1 SKU",
  "Pack1 Barcode",
  "Pack1 DEF Retail Price",
  "Pack1 DEF Buy Price",
  "Pack1 Sellable",
  "Pack1 Purchasable",
  "Pack2 Label",
  "Pack2 Size",
  "Pack2 SKU",
  "Pack2 Barcode",
  "Pack2 DEF Retail Price",
  "Pack2 DEF Buy Price",
  "Pack2 Sellable",
  "Pack2 Purchasable",
  "Pack3 Label",
  "Pack3 Size",
  "Pack3 SKU",
  "Pack3 Barcode",
  "Pack3 DEF Retail Price",
  "Pack3 DEF Buy Price",
  "Pack3 Sellable",
  "Pack3 Purchasable",
] as const;

/** Row 2 of the Simple template: the importer's own column specifications. */
export const SIMPLE_UPLOAD_SPEC_ROW: readonly string[] = [
  "Text | required",
  "Text | required | unique in the file and in the system",
  "Text",
  "Text",
  "Text | from supplier",
  "Text",
  "Text",
  "Text | optional | public JPEG/PNG image URLs | separate multiple urls with comma | each image up to 2 MB | up to 30 images per product",
  "list \nyes \nno \nDefault yes",
  "list \nyes \nno \nDefault yes",
  "list \nyes \nno \nDefault yes",
  "list \nyes \nno \nDefault no",
  "list \nyes \nno \nDefault no",
  "list \nyes \nno \nDefault no",
  "Number",
  "Number",
  "Number",
  "Number",
  "Number",
  "Text | from tax | the default tax if empty",
  "Number",
  "Text | The pack label | main product rate 1 does not need it | required if the product packed",
  "Number | required if the product pack",
  "SKU | from product in system or in the file | required one product at least",
  "Text",
  "Number",
  "Number",
  "list \nyes \nno \nDefault yes",
  "list \nyes \nno \nDefault yes",
  "Text | The pack label | main product rate 1 does not need it | required if the product packed",
  "Number | required if the product pack",
  "SKU | from product in system or in the file | required one product at least",
  "Text",
  "Number",
  "Number",
  "list \nyes \nno \nDefault yes",
  "list \nyes \nno \nDefault yes",
  "Text | The pack label | main product rate 1 does not need it | required if the product packed",
  "Number | required if the product pack",
  "SKU | from product in system or in the file | required one product at least",
  "Text",
  "Number",
  "Number",
  "list \nyes \nno \nDefault yes",
  "list \nyes \nno \nDefault yes",
];

export const COMPOSITE_UPLOAD_HEADERS = [
  "Product Name",
  "Product SKU",
  "Barcode",
  "Sellable",
  "Category",
  "Supplier",
  "Brand",
  "Description",
  "Image URLs",
  "Retail Price",
  "Wholesale Price",
  "Online Price",
  "Tax Code",
  "Product1 SKU",
  "Product1 Rate",
  "Product2 SKU",
  "Product2 Rate",
  "Product3 SKU",
  "Product3 Rate",
  "Product4 SKU",
  "Product4 Rate",
  "Product5 SKU",
  "Product5 Rate",
  "Product6 SKU",
  "Product6 Rate",
  "Product7 SKU",
  "Product7 Rate",
  "Product8 SKU",
  "Product8 Rate",
  "Product9 SKU",
  "Product9 Rate",
  "Product10 SKU",
  "Product10 Rate",
  "Product11 SKU",
  "Product11 Rate",
  "Product12 SKU",
  "Product12 Rate",
  "Product13 SKU",
  "Product13 Rate",
  "Product14 SKU",
  "Product14 Rate",
  "Product15 SKU",
  "Product15 Rate",
  "Product16 SKU",
  "Product16 Rate",
  "Product17 SKU",
  "Product17 Rate",
  "Product18 SKU",
  "Product18 Rate",
  "Product19 SKU",
  "Product19 Rate",
  "Product20 SKU",
  "Product20 Rate",
  "Product21 SKU",
  "Product21 Rate",
  "Product22 SKU",
  "Product22 Rate",
  "Product23 SKU",
  "Product23 Rate",
  "Product24 SKU",
  "Product24 Rate",
  "Product25 SKU",
  "Product25 Rate",
  "Product26 SKU",
  "Product26 Rate",
  "Product27 SKU",
  "Product27 Rate",
  "Product28 SKU",
  "Product28 Rate",
  "Product29 SKU",
  "Product29 Rate",
  "Product30 SKU",
  "Product30 Rate",
] as const;

/** Row 2 of the Composite template. */
export const COMPOSITE_UPLOAD_SPEC_ROW: readonly string[] = [
  "Text | required",
  "Text | required | unique in the file and in the system",
  "Text",
  "list \nyes \nno \nDefault yes",
  "Text",
  "Text | from supplier",
  "Text",
  "Text",
  "Text | optional | public JPEG/PNG image URLs | separate multiple urls with comma | each image up to 2 MB | up to 30 images per product",
  "Number",
  "Number",
  "Number",
  "Text | from tax | the default tax if empty",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
  "SKU | from product in system or in the file | required one product at least",
  "Number",
];
